### ISSUE TITLE
NPEs in server log

### ISSUE THREAD

**Issue by inponomarev** [dbelob/guess-game#12]
Server log contains a bunch of NPEs:

[guess-game.log.gz](https://github.com/dbelob/guess-game/files/3661874/guess-game.log.gz)

**Comment by dbelob** [comment]
1. NPE error is fixed, see c59fbe628734c19a9802a375b977d58286c94b60
2. Version 1.0.1 is released
3. Application is updated on https://jugspeakers.online site
